# Generated by Django 4.2.6 on 2024-11-11 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_certification_description_certification_poster_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedirector',
            name='role',
            field=models.CharField(blank=True, choices=[('Main Director', 'Main Director'), ('Assistant Director', 'Assistant Director'), ('Co-Director', 'Co-Director'), ('Executive Producer', 'Executive Producer')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='moviegenre',
            name='importance_level',
            field=models.IntegerField(blank=True, choices=[(1, 'Very Low'), (2, 'Low'), (3, 'Medium'), (4, 'High'), (5, 'Very High')], null=True),
        ),
        migrations.AlterField(
            model_name='moviestar',
            name='role',
            field=models.CharField(blank=True, choices=[('Lead', 'Lead'), ('Supporting', 'Supporting'), ('Cameo', 'Cameo'), ('Episodic', 'Episodic')], max_length=20, null=True),
        ),
    ]
